addSbtPlugin("com.scalapenos" % "sbt-prompt" % "0.2.1")
addSbtPlugin("com.orrsella" % "sbt-sound" % "1.0.4")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.5.0")
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.5")
